### ISSUE TITLE
"Side bar width": Percentage breaks Sidebar style

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#59]
When using a percentage (e.g. ``30%``) instead of a fixed value (default: ``300px``) for the sidebar, the following happens:

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/2974895/223116290-eac63979-9220-496e-8c97-13cc9be3da5b.png">

But when setting it to the default value (``300px``), it seems to be working as expected:

![image](https://user-images.githubusercontent.com/2974895/223116194-974d11cc-8dbf-472b-99f4-a9b5fa69e043.png)

Not sure if it's a bug or addressable, but when not specifying a unit (e.g. ``300``), the following happens:

![image](https://user-images.githubusercontent.com/2974895/223116391-c35e0202-39f6-4378-abcd-9911f9be5dad.png)

**Comment by my17560** [comment]
Thank you for your report! I've fixed it.

Please be noted, the width value needs to be a valid CSS value since it is directly placed in CSS. So you need a unit.

**Comment by eduardomozart** [comment]
Hello,
After applying your style, even when applying a fixed width, the search bar doesn't seem aligned to center.

Here's our main Wiki that I did have applied your changes from your last commit:

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/2974895/223407473-726d8479-b82f-47a5-bbfe-bcf1de6ea16b.png">

Here I have a Wiki I didn't have applied those changes from your last commit:

![image](https://user-images.githubusercontent.com/2974895/223407303-116f9812-357f-4104-93e0-3b4afa299a59.png)

**Comment by eduardomozart** [comment]
I'd also noticed that the sidebar text still doesn't seem to be resized when a percentage is used for sidebar width:

![image](https://user-images.githubusercontent.com/2974895/223407847-55166665-7d58-4795-b0b1-ceeb0fca6f2e.png)

**Comment by my17560** [comment]
On my site, the search bar appears correctly. Have you applied your own custom styles to sidebar header?

As for the sidebar not resized issue, which index plugin are you using?

And please make sure the cache is cleared for both issues.

**Comment by my17560** [comment]
I've fixed the styles. Could you try the latest?

**Comment by my17560** [comment]
That's weird. I've already fixed it to "100%". 

line 61 of the below file:
https://github.com/my17560/dokuwiki-template-readthedokus/blob/main/css/sidebar.css

Update failure?
