### ISSUE TITLE
Do not fit screen when percentage is used for page content

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#61]
Hello,
When using 70% for page content, it doesn’t fit full page on iOS devices anymore, as can be seen on grey area below.
![B205F21B-502A-4230-8165-D2E4332FE080](https://user-images.githubusercontent.com/2974895/225559934-7e63f4ce-92ca-4742-89c1-19ac7780100b.png)
I believe it’s happening because there’s no way to setup the proper media size tag on DokuWiki style editor, so it uses the setup value (70%).
![2C709983-D886-4A50-A513-785AA8C18ADE](https://user-images.githubusercontent.com/2974895/225560726-346e76e1-06b6-4481-b08c-56fa725a17a3.png)
I believe the page content should be set 100% for devices lower than 768px or this option could be configurable on DokuWiki style editor as “Page content (mobile devices)”.
It seems fine on Admin page though, because I believe it seems to use the 100% width for centered content.
![60805863-CF7A-49D4-A283-E4526172AF27](https://user-images.githubusercontent.com/2974895/225560924-b316d8a8-d081-4d26-bb41-a5a9345da8cf.png)

**Comment by my17560** [comment]
Thanks for your report. Yes, it should be 100% when the width < 768px.
I've fixed it and committed.

**Comment by eduardomozart** [comment]
Search result pages still seems not fit full page.
![5B84DEDB-AB72-4B6F-BEA0-5E14035AC123](https://user-images.githubusercontent.com/2974895/225982323-c130ac9a-ed08-4f27-84e9-95af864ba6ad.png)

**Comment by my17560** [comment]
Sorry. I've fixed it, too.

**Comment by eduardomozart** [comment]
The “wrong login” error page still doesn’t seem to fit.
![DA416DE0-43AD-4FE5-A94A-E38C6F35E207](https://user-images.githubusercontent.com/2974895/228622710-2f4e8832-3b64-4603-adfd-ad507a70adf8.png)

**Comment by my17560** [comment]
Thanks, I've fixed it.
